#!/bin/bash

# Check requirements
command -v dpkg-sig >/dev/null 2>&1 || { echo >&2 'To start this script, dpkg-sig is required!'; exit 1; }
gpg --list-keys "signing key" >/dev/null 2>&1 || { echo >&2 'To start this script, the gpg key "signing key" is required!'; exit 1; }
[ -z "$@" ] && { echo >&2 'Usage: ./sign.sh package1.deb [package2.deb [...]]'; exit 1; }

# Sign
for f in "$@"; do dpkg-sig -k "signing key" --sign builder $f; done
