#!/bin/bash

if [ -t 1 ]
then
	COLORS="$(tput colors)"
	if test -n "$COLORS" && test $COLORS -ge 8
	then
		#BOLD="$(tput bold)"
		#UNDERLINE="$(tput smul)"
		#STANDOUT="$(tput smso)"
		NORMAL="$(tput sgr0)"
		#BLACK="$(tput setaf 0)"
		#RED="$(tput setaf 1)"
		GREEN="$(tput setaf 2)"
		#YELLOW="$(tput setaf 3)"
		BLUE="$(tput setaf 4)"
		#MAGENTA="$(tput setaf 5)"
		#CYAN="$(tput setaf 6)"
		#WHITE="$(tput setaf 7)"
	fi
fi

help() {
	echo "Usage: dict [word]"
	echo "Translate the given word(s) with dict.leo.org [${GREEN}English${NORMAL} -- ${BLUE}Deutsch${NORMAL}]"
	exit 1
}

[ "$1" == "--help" ] && help

wget -q -O- "https://dict.leo.org/?search=$1" \
	| grep -iA 1 "<td[^>]*data-dz-attr=\"relink\"[^>]*lang=\"[a-z]*\">.*" \
	| sed ':a;N;$!ba;s/\(<td[^>]*>\)\n/\1/g' \
	| sed ':a;N;$!ba;s/\n\([^<]*<\/td>\)/\1/g' \
	| sed "s/<td[^>]*data-dz-attr=\"relink\"[^>]*lang=\"en\">\(.*\)/~g~\1~n~ --i/g" \
	| sed "s/<td[^>]*data-dz-attr=\"relink\"[^>]*lang=\"de\">\(.*\)/~b~\1~n~/g" \
	| sed ':a;N;$!ba;s/--\n//g' \
	| sed ':a;N;$!ba;s/\t/ /g' \
	| sed ':a;N;$!ba;s/<\/*tbody[^>]*>\n*//g' \
	| sed ':a;N;$!ba;s/<\/*td[^>]*>\n*//g' \
	| sed ':a;N;$!ba;s/<\/*tr[^>]*>\n*//g' \
	| sed ':a;N;$!ba;s/<\/*a[^>]*>\n*//g' \
	| sed ':a;N;$!ba;s/<\/*span[^>]*>\n*//g' \
	| sed ':a;N;$!ba;s/<\/*br[^>]*>/ /g' \
	| sed "s/<b>\([^<]*\)<\/b>/\1/g" \
	| sed "s/<sup>\([^<]*\)<\/sup>/\[\1\]/g" \
	| sed "s/<sub>\([^<]*\)<\/sub>/\[\1\]/g" \
	| sed "s/<i>\([^<]*\)<\/i>/\[\1\]/g" \
	| sed "s/<small>\([^<]*\)<\/small>/\1/g" \
	| sed ':a;N;$!ba;s/i\n/ /g' \
	| sed ':a;N;$!ba;s/^\(.*\)\n$/\1/g' \
	| sed "s/ / /g" | sed "s/ / /g" | sed "s/ [ ]*/ /g" | sed "s/ ~\([gbn]\)~ /~\1~ /g" \
	| sed "s/~g~/$GREEN/g" | sed "s/~b~/$BLUE/g" | sed "s/~n~/$NORMAL/g"
	# Note that there are two different kinds of spaces to replace!
