#!/usr/bin/python

from lxml import html
import sys, requests

if sys.stdout.isatty():
	normal = '\033[00m'
	green = '\033[92m'
	blue = '\033[94m'
else:
	normal = ''
	green = ''
	blue = ''

if len(sys.argv) == 1 or sys.argv[1] == '--help':
	print >> sys.stderr, 'Usage: dict "word"'
	print >> sys.stderr, 'Translate the given word(s) with dict.leo.org [' + green + 'English' + normal + ' -- ' + blue + 'Deutsch' + normal + ']'
	print >> sys.stderr
	sys.exit(1)

url = 'https://dict.leo.org/englisch-deutsch/' + sys.argv[1];

r = requests.get(url)
if r.status_code == 200:
	content = html.fromstring(r.content)
	for section in content.xpath('//*[@data-dz-role="section"]/@data-dz-name'):
		print
		print content.xpath('//*[@data-dz-name="' + section + '"]//h2/text()')[0]
		print
		for entry in content.xpath('//*[@data-dz-name="' + section + '"]//*[@data-dz-ui="dictentry"]/@data-dz-rel-uid'):
			en = ' '.join(content.xpath('//*[@data-dz-name="' + section + '"]//*[@data-dz-rel-uid="' + entry + '"]//*[@lang="en"]//text()'))
			de = ' '.join(content.xpath('//*[@data-dz-name="' + section + '"]//*[@data-dz-rel-uid="' + entry + '"]//*[@lang="de"]//text()'))
			en = ' '.join(en.split())
			de = ' '.join(de.split())
			print '  ' + green + en + normal + ' ' * (35 - len(en)) + ' -- ' + blue + de + normal
	print
elif r.status_code == 404:
	print >> sys.stderr, 'Error: ' + sys.argv[1] + ' not found'
	sys.exit(1)
else:
	print >> sys.stderr, 'Error: dict.leo.org returned status code ' + str(r.status_code)
	sys.exit(1)
