#!/bin/bash

SSH="ssh -q"
REMOTE_HOST="username@remote.example.com"
REMOTE_SRC="/path/to/files"
LOCAL_DEST="/local/path"

source "$0.date"
[ -z "$LAST_RUN" ] && LAST_RUN="0000-01-01 00:00:00"

FILES="$($SSH $REMOTE_HOST find "'"$REMOTE_SRC"'" -newermt "'"$LAST_RUN"'" -type f -print 2>/dev/null)"
STAMP="$(date +%Y-%m-%d\ %H-%M-%S)"
IFS=$'\n'

echo "Which file should I copy [y/n on each]?"
echo

for f in $FILES; do
  aw=""
  while [ "$aw" != "y" -a "$aw" != "n" ]; do
    echo -n "  $f: "
    read aw
  done
  if [ "$aw" = "y" ]; then
    SOURCES+=" $REMOTE_HOST:'$f'"
  fi
done

echo

if [ -z $SOURCES ]; then
  echo "Nothing to copy ..."
else
  eval rsync --progress -ze "'"$SSH"'"$SOURCES "'"$LOCAL_DEST"'"
  [ $? -eq 0 ] && echo 'LAST_RUN="'"$STAMP"'"' >"$0.date"
fi
