#!/bin/bash

# Copied from https://github.com/tpo/little_shell_scripts

help() {
	echo "Usage: thunderbird-wake"
	echo "Wake up all thunderbird processes"
	echo "See also: thunderbird-sleep"
	exit 1
}

[ "$1" == "--help" ] && help

pkill -CONT -f "(^|/)+icedove( |$)+"
pkill -CONT -f "(^|/)+thunderbird( |$)+"
